### ISSUE TITLE
Path data not invalid even though it doesn't start with MoveTo.

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#1848]
https://www.w3.org/TR/SVG2/paths.html#PathDataMovetoCommands

![image](https://github.com/thorvg/thorvg/assets/85438892/af7fa5b4-e1f7-4e6c-83ea-2ded9e93fa76)

So if we don't start with a MoveTo command, everything following should be treated as invalid. But ThorVG tries to do something with it nonetheless (see the white shape):

![image](https://github.com/thorvg/thorvg/assets/85438892/afe33ec2-9220-417c-8e05-f69aed2d3966)

`<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="c2 7 2 14 10 5" fill="#fff"/></svg>`

**Comment by JSUYA** [comment]
Hi @hermet 

When using PathCommand (also Path APIs), there is a difference between drawing with {CubicTo, Close} and drawing with {MoveTo, CubicTo, Close}.
If CubicTo does not have an initial point (the previous last point(current point, ctrl point)), it may be decided invalid or an arbitrary initial point of 0,0 can be added internally. However, adding internally may differ from the user's intention.

In order to fix this issue, SVG can add logic that does not draw paths if the path does not start with MoveTo.
However, since the PathCommand rule must come first, please let me know your opinion.

Note: The rules(spec) for PathCommand do not strictly follow the SVG specification.

{CubicTo, Close} case
```cpp
    tvg::PathCommand cmds2[2];
    cmds2[0] = tvg::PathCommand::CubicTo;
    cmds2[1] = tvg::PathCommand::Close;

    //CubicTo 1
    tvg::Point pts2[3];
    pts2[0] = {1, 1.5};      //Ctrl1
    pts2[1] = {1.5, 4.5};      //Ctrl2
    pts2[2] = {9.5, 1};                   //To
    auto shape2 = tvg::Shape::gen();
    shape2->appendPath(cmds2, 2, pts2, 3);     //copy path data
    shape2->fill(255, 255, 0);
    shape2->scale(50);
    if (canvas->push(std::move(shape2)) != tvg::Result::Success) return;
```

{MoveTo, CubicTo, Close} case
```cpp
    tvg::PathCommand cmds2[3];
    cmds2[0] = tvg::PathCommand::MoveTo;
    cmds2[1] = tvg::PathCommand::CubicTo;
    cmds2[2] = tvg::PathCommand::Close;

    //CubicTo 1
    tvg::Point pts2[4];
    pts2[0] = {0, 0};      //Move 0 0
    pts2[1] = {1, 1.5};      //Ctrl1
    pts2[2] = {1.5, 4.5};      //Ctrl2
    pts2[3] = {9.5, 1};                   //To
    auto shape2 = tvg::Shape::gen();
    shape2->appendPath(cmds2, 3, pts2, 4);     //copy path data
    shape2->fill(255, 255, 0);
    shape2->scale(50);
    if (canvas->push(std::move(shape2)) != tvg::Result::Success) return;
```

**Comment by hermet** [comment]
@JSUYA, Thanks your info. The renderer will not guarantee the rendering results when it receives invalid input. Therefore, I suggest the following:
1. Enhance the Shape::appendPath() API to return 'InvalidArgument' if the first path command data does not start with MoveTo.
2. Subsequently, the SVG loader should be modified to discard the paint instance building in case of appendPath()  failure.

**Comment by hermet** [comment]
@MewPurPur I think your issue has been fixed. please double-check the issue with the upcoming v0.11.7 release. thanks.
