### ISSUE TITLE
blending support for gl/webgpu

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1917]
Until now, the ThorVG features, including the RenderMethod interface, have been primarily designed with a focus on the sw_engine behavior. We need to confirm the functionality of the blend() feature for hardware support before proceeding with feature confirmation.

Since the blending methods (refer to tvg::BlendMethod) may require access to the destination pixel data, there might be a need to utilize an intermediate render target for composition. Currently, the rendering sequence does not do this, as we can directly access the target buffer in the case of software rendering engine in the sake of the performance.

I would like to confirm the composition process, with an additional render pass, is inevitably required on the GL side. Or if ThorVG could access the GL canvas target buffer (fbo), this additional step may not be necessary.

**Comment by RuiwenTang** [comment]
OpenGL/GLES has an extension called [EXT_shader_framebuffer_fetch](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_shader_framebuffer_fetch.txt) which can be used to avoid the extra renderpass. But it's an extension and may not be present on all platform.

Other GPU API can read this https://github.com/gpuweb/gpuweb/issues/442

**Comment by SergeyLebedkin** [comment]
One of the solution is to use **compute shaders**, thats allow to read and write textures simultaneously at the same time. The problem is, that compute shaders supports only in **OpenGL 4.2** and **WebGPU**, and did not supports in **WebGL**.

As I can see there are different scenarios for rendering and blending in different APIs (in a case without extensions):

### WebGPU/OpenGL 4.2/Vulkan
 shapes renderer - use render pipeline (vertex and fragmant shaders)
 composition/blending - use compute pipeline (compute shaders)

### WebGL/OpenGL (without compute)
 shapes renderer - render pipeline (vertex and fragmant shaders)
 composition - render pipeline (use a mask and original render targets as a textures, currently by design)
 blending - use additional copy of render target (blit)
