### ISSUE TITLE
Lottie: invalid memory reference

### ISSUE THREAD

**Issue by theashraf** [thorvg/thorvg#2168]
This Lottie file contains some base64 inlined png images. For some reason, after passing it to ThorVG, an invalid memory reference error is thrown in [dotlottie-rs](https://github.com/LottieFiles/dotlottie-rs). I've tested the animation in the ThorVG viewer, and it works fine; however, it doesn't display all the image assets as expected, any ideas ? 

Here is the inlined image assets Lottie JSON file
[lush3n7n.lottie.json](https://github.com/thorvg/thorvg/files/14947413/lush3n7n.lottie.json)

Related issue: https://github.com/LottieFiles/dotlottie-web/issues/170

**Comment by tinyjin** [comment]
Hello, @theashraf.

I have no idea for the runtime error `table index is out of bounds`.
I just see the call stack points `DotLottiePlayer.setFrame`. We should make sure whether the exact issue point is from ThorVG or DotLottie.

I've checked the json file. The file doesn't render all inlined images because the attribute ["e"](https://lottiefiles.github.io/lottie-docs/schema/#/$defs/assets) is set to 0, which means the asset isn't inlined image.

![Screenshot 2024-04-12 at 1 14 21 AM](https://github.com/thorvg/thorvg/assets/11167117/5b1296e5-b4a5-49a0-a61d-581639a8dd24)

After replacing all `"e":0` to `"e":1"`, the images work well.

<img width="1028" alt="Screenshot 2024-04-12 at 1 07 57 AM" src="https://github.com/thorvg/thorvg/assets/11167117/17e71eef-eba9-4577-be4f-e173b2c9f793">

I don't understand why lottie-web renders inline images well even with the `"e":0` option.
I assume It ignores and only checks `data:image/png;base64` header.

However, ThorVG checks that option, so the correct way to render is to set `"e":1"`.

**Comment by theashraf** [comment]
@tinyjin, it's quite challenging to obtain the precise call stack of thorvg due to the multi-level bindings within dotlottie-web. As you mentioned, the issue's origin from the JSON file, where the embed property is expected to be 1 for inlined image assets

Not sure why lottie-web ignores the embed property 😕 , I believe this issue no longer relevant to thorvg in this context

Thank you
