### ISSUE TITLE
lottie: incorrect masking drawing

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2322]
see: https://github.com/LottieFiles/dotlottie-web/issues/214

**Comment by mgrudzinska** [comment]
I can not reproduce using thorvg
I'm using different [file](https://github.com/thorvg/thorvg/files/15462251/m.json), since the original one is formatted in such a way, that nothing in drawn. but the idea is the same. 

thorvg - as expected
<img width="307" alt="Zrzut ekranu 2024-05-28 o 00 58 11" src="https://github.com/thorvg/thorvg/assets/67589014/c76ae747-020d-451e-bdbc-292abe2734a2">

https://lottiefiles.github.io/lottie-docs/playground/json_editor/
<img width="328" alt="Zrzut ekranu 2024-05-28 o 01 01 17" src="https://github.com/thorvg/thorvg/assets/67589014/923fcccf-b67c-4244-96c2-4c5b61669ae6">

**Comment by mgrudzinska** [comment]
it doesn't change the result, but after https://github.com/thorvg/thorvg/pull/2330 we may test the original file from the https://github.com/LottieFiles/dotlottie-web/issues/214
still not reproducing in ThorVG - result is as expected:
<img width="192" alt="Zrzut ekranu 2024-05-30 o 01 27 31" src="https://github.com/thorvg/thorvg/assets/67589014/0599dde2-802c-408d-bbdf-ee0095ffe9fb">

**Comment by hermet** [comment]
@mgrudzinska You are saying the result of the lottie-web is wrong?
![image](https://github.com/thorvg/thorvg/assets/3711518/817b8aba-8273-473e-bfbf-4b3331947d92)

**Comment by mgrudzinska** [comment]
we need to confirm what the author of the org issue used to draw. I don;t think it was thorvg engine

**Comment by hermet** [comment]
it's lottie-web problem.
