### ISSUE TITLE
wg_engine: integrate with thorvg player

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2410]
- [x] Research and prototype the Emscripten build with WebGPU
- [x] Implement the necessary integration logic in the tvgWasm part
- [x] Support Multi-Canvases
- [ ] Integrate with the ThorVG player

**Comment by hermet** [comment]
see also: 
- https://eliemichel.github.io/LearnWebGPU/getting-started/hello-webgpu.html
- https://github.com/gfx-rs/wgpu-native/tree/trunk/examples/capture

**Comment by hermet** [comment]
```
    {
        WGPUSurfaceDescriptorFromCanvasHTMLSelector fromCanvasHTMLSelector;
        fromCanvasHTMLSelector.chain.next = NULL;
        fromCanvasHTMLSelector.chain.sType = WGPUSType_SurfaceDescriptorFromCanvasHTMLSelector;
        fromCanvasHTMLSelector.selector = "canvas";

        WGPUSurfaceDescriptor surfaceDescriptor;
        surfaceDescriptor.nextInChain = &fromCanvasHTMLSelector.chain;
        surfaceDescriptor.label = NULL;

        return wgpuInstanceCreateSurface(instance, &surfaceDescriptor);
    }  
```

**Comment by capnm** [comment]
WGPU / DAWN – which backend is currently used in the development of the `wg_engine`?

**Comment by SergeyLebedkin** [comment]
> WGPU / DAWN – which backend is currently used in the development of the `wg_engine`?

Currently we are using **wgpu_native** pre-builds
Please, see pre-buils
https://github.com/gfx-rs/wgpu-native/releases

**Comment by tinyjin** [comment]
Hello, @SergeyLebedkin.

I'd like to discuss interface for WebGPU initialization part. Since current methods don't support browser to have multiple canvases.

According to wg_engine, WGPUAdapter and WGPUDevice are generated when calling WGContext::initialize. Which means those Adapter and Device could be generated in duplicate.

It's going to happen when we have multiple animations or try to resize more than once.

![CleanShot 2024-08-27 at 17 52 30@2x](https://github.com/user-attachments/assets/7ee95caa-2d02-4ae2-8fd8-9f6cb7087e78)

This function is called, following the steps:
- wasm::resize -> canvas::target -> renderer::target -> context::initialize -> _then the WGContext potentially tries to call adapter and device by multiple._


And this is basic WebGPU usage in multiple canvas, it's written in JavaScript, but you can understand the logic.

https://webgpufundamentals.org/webgpu/lessons/webgpu-multiple-canvases.html

![CleanShot 2024-08-27 at 17 57 32@2x](https://github.com/user-attachments/assets/fe033a39-a6f9-4c5f-af75-6910cdba69ef)

As you can see, the adapter and device are initialized in the head of code and reused. Even if they have more than one canvases, the code guarantee it's called only once.

Seeming like browser returns out of memory error, specifically when we send requestAdapter/Device calls again.

Hence in my opinion, we should guarantee that the one page has only adapter and device.
- WGPUInstance, WGPUAdapter, WGPUDevice should be singleton instance and shared by multiple players.
- We will take reusable WGPUInstance, WGPUAdapter, WGPUDevice approach.
- `Request adapter`, `request device` should be called while instance and surface are being ready from out of WGContext.


To do this, these methods will be affected, or something more else.
```cpp
Result target(void* instance, void* surface, **void* adapter, void* device**, uint32_t w, uint32_t h) noexcept;

void WgContext::initialize(WGPUInstance instance, WGPUSurface surface, **WGPUAdapter adapter, WGPUDevice device**)
```

Let's disuss :)

Just for sharing, I've succeed to draw multiple animations by changing the interfaces I mentioned. The only thing I need is to have reasonable interface for the change.

![image](https://github.com/user-attachments/assets/6a43516b-dbcc-4bd8-9693-689458997cff)

**Comment by SergeyLebedkin** [comment]
Please, take a look on https://github.com/thorvg/thorvg/pull/2695

**Comment by hermet** [comment]
@tinyjin Could you please confirm whether overlaying other elements on the WGPU canvas is working properly?
![image](https://github.com/user-attachments/assets/3b2a1de5-f523-42e0-a29b-12057a76ff45)

@SergeyLebedkin Please double-check that the current WGPU canvas doesn't work properly with a transparent background.

**Comment by tinyjin** [comment]
![CleanShot 2024-08-29 at 13 41 17@2x](https://github.com/user-attachments/assets/71b5b35f-0e7e-47a0-b178-caf5f0592e24)

Yes, @hermet. It's doable.
HTML element overlay including the text goes with WebGPU well.

**Comment by SergeyLebedkin** [comment]
@hermet 
> Please double-check that the current WGPU canvas doesn't work properly with a transparent background.
i.e) background should be transparent, (not black)

Do you mean in system apps or in browser? In any case by default alpha channel in the target buffer are 0

**Comment by hermet** [comment]
@SergeyLebedkin Yes but, it doesn't look like it on web.  @tinyjin the masking sample the above, the background color should be white, doesn't it? Could you please confirm this?

**Comment by SergeyLebedkin** [comment]
> Please double-check that the current WGPU canvas doesn't work properly with a transparent background.
i.e) background should be transparent, (not black)

For a proper fix transparent bg emsdk should fix wasm workflow
See https://github.com/emscripten-core/emsdk/issues/1443

**Comment by hermet** [comment]
@tinyjin Hello, the fix looks went into the emscripten core main, could you please check & try with this change in emscripten locally?  https://github.com/emscripten-core/emscripten/pull/22494

**Comment by tinyjin** [comment]
@hermet @SergeyLebedkin 

Confirmed the update(https://github.com/emscripten-core/emscripten/commit/c82a307c612d430028a3d06ddf8b3fdd2852b2fb) enables WebGPU with premultiplied alpha mode in the browser.

![CleanShot 2024-09-06 at 13 53 33@2x](https://github.com/user-attachments/assets/ce04445c-d9b4-4e1c-8bbf-bf1514653d40)

**Comment by hermet** [comment]
Tossed the issue to the ThorVG web project. => https://github.com/thorvg/thorvg.web/pull/49
