### ISSUE TITLE
Inquiry about using canvas

### ISSUE THREAD

**Issue by SUNGHWAN-OH-KR** [thorvg/thorvg#2443]
hello.
I am a thorvg user.
I have a question.

There is no problem when the tvg::SwCanvas::gen() function is used sequentially, but when used asynchronously, the program crashes.
Is there a problem if I use the tvg::SwCanvas::gen() function asynchronously? If there is no problem, please check if there is another way to use it.
The following is an example of use and an image when a problem occurs. Please refer to it.

The following is an example of use, so please refer to it.

auto canvas = tvg::SwCanvas::gen();
auto shape = tvg::Shape::gen();
shape->appendRect(0, 0, (float)width, (float)height);
shape->fill(0, 0, 0);
canvas->push(std::move(shape));

**Comment by hermet** [comment]
> when used asynchronously,

@SUNGHWAN-OH-KR Hello, it's a bit ambiguous. How did you make it asynchronous in your example? could you try please try with engine initialization?

```
if (tvg::Initializer::init(0) == tvg::Result::Success) {
  auto canvas = tvg::SwCanvas::gen();
  auto shape = tvg::Shape::gen();
  shape->appendRect(0, 0, (float)width, (float)height);
  shape->fill(0, 0, 0);
  canvas->push(std::move(shape));

   tvg::Initializer::term();
}
```

**Comment by gellston** [comment]
hello

I think my co-worker didn't explain things in detail. 

Exactly the same code as you described, we have created a class and are calling it from multiple threads with different instances. 

When I first created the class, I designed and used tvg::Initializer::init and tvg::Initializer::term so that they would be called only once in all classes. 
(using Nifty Counter : https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Nifty_Counter) 

So, to summarize, the questions our development team has are as follows.

1. Should tvg::Initizlier::init and tvg::Initializer::term be executed only once after program execution?

2. Pointers to canvas or shape objects are copied and used as member variables within the class through std::move. Should I create all the actions inside one function and do all the rendering? 

3. Is it safe to use the classes you designed, especially canvas, shape, font, etc., in parallel on instances of other classes? Especially loading fonts

Our team is using this render engine to create the resulting image. Images are being created in different threads.

@hermet

**Comment by hermet** [comment]
@gellston hello, 

> * Should tvg::Initizlier::init and tvg::Initializer::term be executed only once after program execution?

yes, definitely.

> * Pointers to canvas or shape objects are copied and used as member variables within the class through std::move. Should I create all the actions inside one function and do all the rendering?

It's the recommended usage. However, you can grab pointers to the TVG instances to access them as needed. Please check `examples/DirectUpdate.cpp` (the simplest code suggested) to see how it holds the shape with the class member and updates its properties dynamically.

> * Is it safe to use the classes you designed, especially canvas, shape, font, etc., in parallel on instances of other classes? Especially loading fonts

No, the APIs are not thread-safe. Canvas and its associated drawing commands like Shape, Picture, etc must be requested in the same thread (either main or worker-thread). 

Otherwise, you can guarantee the thorvg calls  in the main thread, Basically, ThorVG has an intrinsic threading mechanism to help your program accelerate with parallelization. You can designate the number of threads to use in the ThorVG engine like this:

```
auto threadCnt = 4;
tvg::Initizlier::init(threadCnt);
```

**Comment by gellston** [comment]
It seems to be becoming clearer now. 

Last question.

So, will it be a problem if I perform tvg::Initializer::init, tvg::Initializer::term, and font load and unload in the mian thread, and only the drawing operation is performed in a single worker thread? . 

1. start init (font, engine) 
2. drawing loop in different one thread
3. Stop thread when program ends
4. unload (font, engine) from main thread

oh.. by the way 

By the way... the thorvg version in vcpkg is not the latest version. Is it possible to update it? I'm using it by building it manually, but I don't trust my hands.

@hermet

**Comment by hermet** [comment]
> So, will it be a problem if I perform tvg::Initializer::init, tvg::Initializer::term, and font load and unload in the mian thread, and only the drawing operation is performed in a single worker thread? .

It will be a problem. The main idea is to ensure the same thread performs the operation among main or worker threads.

run all on the main thread => ok
```
start init (font, engine)
drawing loop in different one thread
Stop thread when program ends
unload (font, engine) from main thread
```

run all on a worker thread N => ok
```
start init (font, engine)
drawing loop in different one thread
Stop thread when program ends
unload (font, engine) from main thread
```



> By the way... the thorvg version in vcpkg is not the latest version. Is it possible to update it? I'm using it by building it manually, but I don't trust my hands.

Please try building manually. The vcpkg update is planned with ThorVG v0.14 release.
