### ISSUE TITLE
SVG "transparent" keyword not handled

### ISSUE THREAD

**Issue by MewPurPur** [thorvg/thorvg#2772]
I didn't find this anywhere on the SVG specification, but the way I discovered this was missing was from trying to render one of the SVGs on this page: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients (you can find it by searching for `"transparent"`)

I thought it might be an uncommon feature that's not supported by accident.

**Comment by mgrudzinska** [comment]
can be easily supported, since seems to be working exactly like fill="none", right? 
but I also don't see anything about that in svg specs, so not sure if we want to add this

**Comment by JSUYA** [comment]
The value of [`fill` is `<paint>`](https://www.w3.org/TR/SVG2/painting.html#SpecifyingFillPaint), and [`<paint>` can be a `<color>`](https://www.w3.org/TR/SVG2/painting.html#SpecifyingPaint) value, and it seems that `transparent` is included in the [syntax of `<color>`.](https://www.w3.org/TR/css-color-5/#color-syntax)

```
<paint> = none | <color> | <url> [none | <color>]? | context-fill | context-stroke
```
```
<color> = <color-base> | currentColor | <system-color> | <device-cmyk()>  | <light-dark()>
<color-base> = <hex-color> | <color-function> | <named-color> | <color-mix()> | transparent
```
I haven't done a detailed review yet, but since we are using the alpha value of fill(r, g, b, a) as fill.opacity, if we support transparent, we may need to add an alpha memeber to distinguish it.

**Comment by MewPurPur** [comment]
If this is based on the transparent channel, then I suppose it's not necessary.

**Comment by MewPurPur** [comment]
Closing as this requires way more fundamental reworks.
