### ISSUE TITLE
gl_engine: radial gradient fill regression bug Support radial gradient fill SVG2 extension

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2972]
![image](https://github.com/user-attachments/assets/5572bd47-4a66-4462-bb6b-2d1a12fbb0da)

That visual is not appeared after this patch:

```
commit e82830147c7e30686f98624170c995963db5ae31
Author: RuiwenTang <tangruiwen1989@gmail.com>
Date:   Wed Nov 6 12:33:49 2024 +0800

    gl_engine: Support new radial gradient data struct and calculation

    Change the shader and uniform struct to support new radial gradient.
    The mathematical calculation comes from https://skia.org/docs/dev/design/conical/
```

Please save as:
![radial_gradient_focal_outside_circle](https://github.com/user-attachments/assets/fcf3ac28-5b2f-44d9-9207-27e4b44eb6f7)

**Comment by mgrudzinska** [comment]
Now GL seems to be the only engine that support the SVG 2 requirements: https://www.w3.org/TR/SVG2/pservers.html#RadialGradientNotes

samples (focal1 is the example from this issue, I just change the white color to be blue) 
[focal1.svg.zip](https://github.com/user-attachments/files/17803904/focal1.svg.zip)
[focal2.svg.zip](https://github.com/user-attachments/files/17803905/focal2.svg.zip)

results:
<img width="500" alt="Zrzut ekranu 2024-11-18 o 18 04 51" src="https://github.com/user-attachments/assets/63847eba-c891-4ab3-8329-2713c6302d46">

expected:
<img width="250" alt="Zrzut ekranu 2024-11-18 o 18 07 28" src="https://github.com/user-attachments/assets/eb22c865-78b1-44c3-aa9e-303bf02d6316">
<img width="250" alt="Zrzut ekranu 2024-11-18 o 18 07 40" src="https://github.com/user-attachments/assets/54458b15-6db5-4978-9ebe-4f44d8327c86">

so the issue is rather on the sw/wg engine side
